name: Kelsey Lynn Coaching
favicon: null
layout_spectrum: 0.9211691038217396
typography_spectrum: 0.6491851441096514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7871223827823997
  lightness: 0.7606326742097735
  saturation: 0.19726012065075338
  rhythmicContrast: 0.6333698234520853
purpose: []
