name: Kelsey Lynn Coaching
favicon: null
layout_spectrum: 0.98023
typography_spectrum: 0.46041
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ddc9ae'
    - '#29304a'
    - '#6c7184'
    - '#7a4a24'
  brandStrength: 0.9375
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
